# Generated by Django 3.2.5 on 2021-07-13 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EarthQuakeFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('latitude', models.DecimalField(decimal_places=2, max_digits=4)),
                ('longitude', models.DecimalField(decimal_places=2, max_digits=4)),
                ('magnitude', models.DecimalField(decimal_places=1, max_digits=2)),
                ('time', models.DateTimeField()),
            ],
        ),
    ]
